# Attendance

**Note**: Until further notice, all seminars are offered via Zoom or Webex. Please see the information below for specifics.

## Lab meetings

Attendance at lab meetings is mandatory. If you are unable to attend, please notify Mark in advance. We currently meet every two weeks via Zoom.

## SAFS seminar

Attendance at the SAFS weekly seminar on Thursday afternoons is mandatory. During Fall and Spring quarters, seminars run from 4:00-5:00. You can find the schedule for Fall and Spring [**here**](https://fish.uw.edu/news-events/seminar-series/departmental-seminars/). During Winter quarter, SAFS host the Bevan Seminar Series, which runs from 4:30-5:30 to align with normal course begin/end times. You can find the schedule [**here**](https://fish.uw.edu/news-events/seminar-series/bevan-series/).

## SAFS quantitative seminar

Attendance at the SAFS weekly quantitative seminar is optional, but strongly encouraged. Seminars run from 12:30-1:30 on Fridays. You can find the schedule [**here**](https://fish.uw.edu/news-events/seminar-series/quantitative-seminar/).

## Fish & Wildlife ecology seminar



