# (PART) Background {-}

# Lab culture & values

We are dedicated to providing a welcoming and supportive environment for all people, regardless of their background, identity, appearance, or manner of communication. Our team works in an open science environment, relying on trust and respect to build effective partnerships. We continually strive to improve and expand upon our complementary skillsets through education and innovation, and we believe strongly in the sharing of knowledge through conversation and writing.

## Our mission

Using our knowledge and skills to help solve real-world problems.

## Our vision

Our vision is to better understand and manage aquatic ecosystems through the integration of data, analysis, and communication.

## Our philosophy

* [We focus on what is best for all of us]

* [We learn from our mistakes]

* [We respect different viewpoints and experiences]

* [We listen with intent to understand]

* [We show out]

* [We celebrate our successes]

* [We gracefully accept constructive criticism]

* [We are open to change]

* [We consider the impact of our intent]

* [We embrace life outside of academia]


### We focus on what is best for all of us {-}

Our lab is meant to be a safe and welcoming place for all of us. We will all feel better and have greater success in our endeavors when we focus on the collective good. We ask one another for help when needed and we graciously help each other when we can.


### We learn from our mistakes {-}

Science is a process that advances through the acknowledgment of mistakes and a desire to learn from them. We don't set out to fail, but sometimes it just happens. Rather than beat ourselves up about it, we take the time to understand what happened, think about how it could be avoided in the future, and move along.


### We respect different viewpoints and experiences {-}

We all come from different places and different backgrounds. We all have unique experiences and knowledge that we can share with one another. We respect that not everyone has to feel or act the same, and that a diversity of viewpoints is part of what makes us human.


### We listen with intent to understand {-}

When we communicate with others, we listen with the intent to understand where others are coming from and how their previous experiences shape their beliefs. We are active listeners and approach conversations with an open mind.


### We gracefully accept constructive criticism {-}

Science involves a lot of feedback from others. This might be in the form of written comments on a manuscript, a review of some code, or a back-and-forth discussion around a presentation. We acknowledge that we are always learning and looking for better ways of doing our work. As such, we accept *constructive* criticism from one another in the hope of improving ourselves.


### We are open to change {-}

Science is an evolving process where new discoveries bring new ways of thinking and conducting our research. We are committed to exploring new ideas and approaches, and we welcome each other's thoughts.


### We consider the impact of our intent {-}

Although we may set out with the best intentions, our words and actions may have unintended consequences. The impact of our behaviors can make others feel unwelcome, unwanted, or unsafe. Thus, we try our best to consider the impact of our intent, with the understanding that we can also try to repair any damage we may have unwillingly caused to others.


### We show out {-}

We don't merely show up--we show out! We put our best selves forward and commit to working hard. Simply "going through the motions" won't get you very far in our lab.


### We celebrate our successes {-}

Science has its ups and, unfortunately, more than enough downs. It's important that we acknowledge our successes and celebrate accordingly, whether they be small wins or major accomplishments. We're not shy about giving someone a high-five or a pat on the back.


### We embrace life outside of academia {-}

Academia can be fun and exciting, but so can lots of other things. We believe that a healthy lifestyle outside of academia helps us be better scientists, as well as better colleagues and friends to one another. Our families, friends, pets, neighbors, and communities are all important parts of our lives and they deserve some of our attention as well.

