# (APPENDIX) Appendices {-}

# Resources on JEDI in STEM

<br>

Here are some resources to help educate ourselves about racism and colonialism in STEM and society as a whole, and things we can do to help change the status quo.

## Collection of resources from UW

* [Race & Equity Initiative](https://www.washington.edu/raceequity/2020/06/10/race-and-equity-resources/)

## Websites

### General

* [BlackPast](https://www.blackpast.org/)

* [Coalition of Anti Racist Whites](https://www.carw.org/)

* [Guide to Allyship](https://guidetoallyship.com/)

### Stem

* [#ShutDownSTEM](https://www.shutdownstem.com/)

* [VanguardSTEM](https://www.vanguardstem.com/)

* [500 Women Scientists](https://500womenscientists.org/)

## Online articles & blogs

* Jasmine Robert's piece on [white supremacy in academia](https://medium.com/the-faculty/white-academia-do-better-fa96cede1fc5)

* Rian Roberson's piece on [white allies](https://medium.com/@mxmetalrian/white-allies-give-your-black-and-brown-friends-some-space-71aeab400a15)

* Rian Roberson's piece on [Black History 2020: Living Legends](https://medium.com/@mxmetalrian/black-history-2020-living-legends-626965dadec9)

* [An open letter to the EEB community](https://medium.com/@solonorthrowan/an-open-letter-to-the-eeb-community-7bd89330e554)

## Books

* _How to Be Anti-Racist_ by Ibram X. Kendi

* _White Fragility_ by Robin Diangelo

* _So You Want to Talk About Race_ by Ijeoma Oluo

* _Me and White Supremacy_ by Layla F. Saad

* _The New Jim Crow_ by Michelle Alexander

* _Eloquent Rage: A Black Feminist Discovers Her Superpower_ by Brittany Cooper

* _Reproductive Injustice: Racism, Pregnancy, and Premature Birth_ by Dána-Ain Davis

* _Beyond Inclusion, Beyond Empowerment_ by Leticia Nieto

* _My Grandmother’s Hands_ by Resmaa Menaken

* _Post Traumatic Slave Syndrome_ by Joy DeGruy

## Journal articles

Asai, D. J. (2020). Race Matters. Cell, 181(4), 754–757. https://doi.org/10.1016/j.cell.2020.03.044

Beltran, R. S., Marnocha, E., Race, A., Croll, D. A., Dayton, G. H., & Zavaleta, E. S. (n.d.). Field courses narrow demographic achievement gaps in ecology and evolutionary biology. Ecology and Evolution. https://doi.org/10.1002/ece3.6300

Blosser, E. (2020). An examination of Black women’s experiences in undergraduate engineering on a primarily white campus: Considering institutional strategies for change. Journal of Engineering Education, 109(1), 52–71. https://doi.org/10.1002/jee.20304

Dutt, K. (2020). Race and racism in the geosciences. Nature Geoscience, 13(1), 2–3. https://doi.org/10.1038/s41561-019-0519-z

Fovet, F. (2020). Beyond Novelty: “Innovative” Accessible Teaching as a Return to Fundamental Questions Around Social Justice and Reflective Pedagogy. https://www.igi-global.com/chapter/beyond-novelty/252132

Gautreaux, M. (2018). Towards shared understandings: An exploration of the literature on inclusive teaching and its implication for building Inclusive Excellence at UBC.

Kang, S. P., Chen, Y., Svihla, V., Gallup, A., Ferris, K., & Datye, A. K. (n.d.). Guiding change in higher education: an emergent, iterative application of Kotter’s change model. Studies in Higher Education, 20. https://doi.org/10.1080/03075079.2020.1741540

Kim, S. S., & Gelfand, M. J. (2003). The influence of ethnic identity on perceptions of organizational recruitment. Journal of Vocational Behavior, 63(3), 396–416. https://doi.org/10.1016/s0001-8791(02)00043-x

Knaub, A. V, Maier, S. J., & Ding, L. (2020). Changing Culture and Climate to Prevent Sexual Harassment in the Physics Educational Setting. Physics Teacher, 58(5), 352–355. https://doi.org/10.1119/1.5145535

O’Brien, L. T., Bart, H. L., & Garcia, D. M. (2020). Why are there so few ethnic minorities in ecology and evolutionary biology? Challenges to inclusion and the role of sense of belonging. Social Psychology of Education, 23(2), 449–477. https://doi.org/10.1007/s11218-019-09538-x

Quan, G. M., Corbo, J. C., Finkelstein, N. D., Pawlak, A., Falkenberg, K., Geanious, C., Ngai, C., Smith, C., Wise, S., Pilgrim, M. E., & Reinholz, D. L. (2019). Designing for institutional transformation: Six principles for department-level interventions. Physical Review Physics Education Research, 15(1), 22. https://doi.org/10.1103/PhysRevPhysEducRes.15.010141

Reinholz, D. L., Matz, R. L., Cole, R., & Apkarian, N. (2019). STEM Is Not a Monolith: A Preliminary Analysis of Variations in STEM Disciplinary Cultures and Implications for Change. Cbe-Life Sciences Education, 18(4). https://doi.org/10.1187/cbe.19-02-0038

Riegle-Crumb, C., King, B., & Irizarry, Y. (2019). Does STEM Stand Out? Examining Racial/Ethnic Gaps in Persistence Across Postsecondary Fields. Educational Researcher, 48(3), 133–144. https://doi.org/10.3102/0013189x19831006

Rosa, K., & Mensah, F. M. (2016). Educational pathways of Black women physicists: Stories of experiencing and overcoming obstacles in life. Physical Review Physics Education Research, 12(2). https://doi.org/10.1103/PhysRevPhysEducRes.12.020113

Smith, N. S., Côté, I. M., Martinez-Estevez, L., Hind-Ozan, E. J., Quiros, A. L., Johnson, N., Green, S. J., Cornick, L., Shiffman, D., Malpica-Cruz, L., Besch, A. G., & Shiel-Rolle, N. (2017). Diversity and inclusion in conservation: A proposal for a Marine Diversity Network. Frontiers in Marine Science, 4(AUG). https://doi.org/10.3389/fmars.2017.00234

## Videos

* [TED and TEDx talks](https://www.youtube.com/playlist?list=PLDToukXRDVMSkxrabFfSb5u6cE82huRpD&fbclid=IwAR1nnLa9DPMjwp4GlzhGaIr-Hvrgs0hAlpBsW2qKZDSMODLnnDPJCJvV1GA) about racism and actions to eliminate it

* [TED and TEDx talks](https://www.ted.com/playlists/250/talks_to_help_you_understand_r) to help you understand racism in America

* [FISH 513 Cultivating Inclusive Conservation Practices (hosted by Dr. Staci Amburgey)](https://www.youtube.com/playlist?list=PLgDT5hypdTyTg7UaUth5Ba8oIzwRxwlxT) a very informative seminar series that delves into DEI issues in conservation.

## Podcasts

* [Code Switch](https://www.npr.org/podcasts/510312/codeswitch)

* [Still Processing](https://www.nytimes.com/column/still-processing-podcast)

* [The Daily](https://www.nytimes.com/column/the-daily)

* [1619](https://www.nytimes.com/2020/01/23/podcasts/1619-podcast.html)

* [Pod Save the People](https://crooked.com/podcast-series/pod-save-the-people/)

## Twitter

* [#IndigenousSTEM](https://twitter.com/hashtag/disabledandSTEM) [#NativeandSTEM](https://twitter.com/hashtag/NativeandSTEM) [#NativeScience](https://twitter.com/hashtag/NativeScience)

* [#WomenInSTEM](https://twitter.com/hashtag/WomenInSTEM)

* [#lgbtSTEM](https://twitter.com/hashtag/lgbtSTEM)

* [#blackandSTEM](https://twitter.com/hashtag/blackandSTEM) [#BlackInTheIvory](https://twitter.com/hashtag/BlackInTheIvory) [#BlackAFinSTEM](https://twitter.com/hashtag/blackAFinSTEM)

## Black-owned businesses

* List of Black-owned businesses in WA from [Support Black Owned](https://www.supportblackowned.com/states/wa)
