# (PART) Health & safety {-}

# Health & well-being

### **If you are experiencing an emergency, dial 911 immediately!** {-}

<br>

Your health and well-being are of paramount importance. For a broad range of resources and assistance at UW, please see the [Husky Health & Well-Being website](https://wellbeing.uw.edu/).

## Health insurance

### Students

Academic student employees (ASEs) receive health insurance through the [Graduate Appointee Insurance Program (GAIP)](https://hr.uw.edu/benefits/insurance/health/graduate-appointees-options/). GAIP covers medical, vision, and dental care for teaching assistants, research assistants, tutors, predoctoral researchers, and other ASEs working across the University.

GAIP benefits are negotiated between the UW and United Auto Workers (representing students at UW) on a three-year basis. The benefits are administered by LifeWise, a health insurance company based in the Pacific Northwest.

#### Eligibility

The UW pays for your GAIP coverage if you hold an eligible job appointment and meet all these requirements:

* You enroll for at least 10 credits during the quarter

* You’re position is at least 50% full-time equivalent

* You’re paid on at least five of the six pay days of the coverage period

* You register for classes by the 10th day of each quarter

This eligibility criteria applies to the fall, winter, and spring quarters. If you remain eligible throughout these three quarters, you’ll automatically receive summer quarter coverage.

#### Enrollment

You don't need to enroll yourself in GAIP. Instead, your eligibility is established when your department enters your employment information into Workday. However, to avoid any coverage delays, you should contact your department and verify your employment information was entered into Workday if you haven't received enrollment confirmation.

Once enrolled, you'll receive an enrollment confirmation email from LifeWise, the plan administrator. Please make sure to read all the GAIP information you receive as it contains important information about the GAIP plan.

### Post-docs & technicians

Post-docs and technicians should investigate the options available from the insurance provider you select when you sign up for UW Benefits. For example, through Regence you have access to a free service called Quartet, which helps you find a therapist based on your particular concern, and will also help you change therapists until you find the right fit.


## Mental health

Every one of us can be negatively affected by a wide range of factors, whether or not they be related to academics. If you should feel like you need some help, please consider the following resources.

[**Crisis Clinic**](http://www.crisisclinic.org/)  
Phone: 206-461-3222 or toll-free at 1-866-427-4747   

[**UW Counseling Center**](https://www.washington.edu/counseling/services)  
Phone: 206-543-1240  
[Immediate assistance](https://www.washington.edu/counseling/services/crisis/)

[**Let’s Talk**](https://wellbeing.uw.edu/virtual-lets-talk/)

[**Hall Health Mental Health**](https://wellbeing.uw.edu/unit/hall-health)


## Sick leave

If you are not feeling well, please be considerate of others in the lab and the SAFS community and stay home. If you have a meeting, deadline, exam, or other activity that would otherwise require you to be here, please do your best to reschedule it for another time when you're feeling better. Grad students accrue sick leave at the rate of one (1) hour for every 40 hours worked. Sick leave accrues at the end of the month and is available for use the following month. Postdocs receive one day of paid sick time off for every month of their appointment. Paid sick time off will be preloaded annually and available at the beginning of the month following the start of the appointment. Please note, though, that Mark will provide you with an excused absence if you are sick, but out of leave time.


## Food Pantry

No student should ever have to choose between buying food or textbooks. The UW Food Pantry helps mitigate the social and academic effects of campus food insecurity. They aim to lessen the financial burden of purchasing food by providing students access to shelf-stable groceries, seasonal fresh produce, and hygiene products at **no cost**. Students can expect to receive 4 to 5 days' worth of supplemental food support when they visit the Pantry, located on the north side of Poplar Hall at the corner of NE 41<sup>st</sup> St and Brooklyn Ave NE. Visit the [Any Hungry Husky website](https://uw.edu/anyhungryhusky) for additional information, including operating hours and additional food support resources.
