# (PART) Lab & Field {-}

# In the lab

[ more info coming soon ]

## General etiquette and advice

*	Wash all equipment that has been used and leave out to dry. 

*	Keep lab counter spaces clear of clutter. 

*	Never store samples or chemicals outside of the lab.


## Eyewash

During times when the lab is used regularly, we must flush the eyewash system with 10 gallons of water _every week_. There is a dedicated and marked 5-gallon bucket on the floor next to the eyewash. To flush the system, make sure the bucket is under the white drain pipe and then gently push the activation lever until water starts coming out both holes and drains into the bucket. When the bucket is nearly full, turn off the water by pulling back on the lever and then empty the bucket into the sink. Repeat the process a second time and then record the date and your initials on the sheet in the paper rack near the microscope.


## Fume hood

In order to help keep the fume hood relatively unobstructed, only chemicals that are actively being used should be in the fume hood. Extra chemicals should be stored in their proper cabinet. Be careful to not exceed the open height limit denoted on the edges of the sash.

Also note that on occasion the hood's alarm gets triggered accidentally, which activate a high pitch whine. If you hear it and you don't see any obvious problems, press the "reset" button on the hood controls located on the right side of the hood at about head height.


## Chemicals

Mark maintains a chemical inventory and tracks it with MyChem. Please consult with him before purchasing any new chemicals. With the exception of standard household cleaning supplies (windex, all purpose cleaner, soap etc) all chemicals should be stored in the fume hood (temporarily), or in the chemical storage cabinets under and to the left of the fume hood. You can access safety data sheets (SDS) [here](https://www.ehs.washington.edu/chemical/safety-data-sheets-sdss).

### Flammables

All flammable chemicals must be kept inside the dedicated flammable cabinet under the fume hood. 


## Sample storage

All samples, independent of where they are stored, should be labeled with the following information _at a minimum_:

* Date

* Sample contents

* Type of preservative, if not frozen (e.g., ethanol)

* Name of person responsible or name of project


## Gear & equipment

* All field gear should be cleaned well and hung to dry on the wire rack or on the large water table. 

* Coolers should be kept under the water table. 

* Wading boots should be placed in the freezer for at least 24 hours to kill small organisms and help prevent the spread of nonnative species.

