# Coop Unit

<p></p>

Mark's faculty appointment in SAFS is tied to his position as the Assistant Unit Leader for Fisheries in the [U.S. Geological Survey Washington Cooperative Fish and Wildlife Research Unit](https://depts.washington.edu/wacfwru/) (WACFWRU or "Coop Unit"). Therefore, as a member of the Applied Ecology Lab you are also a member of the Coop Unit. Other members of the WACFWRU include:

* [Dr. Sarah Converse](https://fish.uw.edu/faculty/sarah-converse/) (Unit Leader) and her lab members

* [Dr. Alex McInturff](https://alexmcinturff.com/) (Assistant Unit Leader - Wildlife) and his lab members

* [Sarah Romero](mailto:sarahjh@uw.edu) (WACFWRU administrator)

Because the Coop Unit is a federal program and Mark is a federal employee, there are a few things that apply to you, but not other SAFS students or employees. Most of these are benefits, but there are some additional policies and procedures that must be followed. Sarah Romero can help you with many of the administrative tasks and will be a resource on a wide variety of topics. 


### Volunteer forms

Everyone in the unit who is not a federal employee (i.e., students, postdocs, technicians) will need to complete a volunteer agreement as part of the onboarding process, which can be found [here](resources/USGS_Form_9_2080_fillable.pdf). Please fill in the following information

* Sec 1: Personal information
* Sec 2: Emergency contact
* Sec 3a: Beginning & end dates (ask Mark for these)
* Sec 3f: Sign and date the document (digitally is OK)

When you are finished, email the form to Mark. He will then sign it and file it with our records.


### Digital Measures

Digital Measures (DM) is the online system that the national Cooperative Units Program uses to track nearly everything, including students/post-docs who are part of the program, what research projects are ongoing, what publications/presentations are in the works, and safety training requirements. Sarah Romero will be able to help you get set up with a DM account. As soon as you're set up with a DM account, you'll need to do your own Personal Hazard Analysis, which will create a list of safety training that you'll need to take. Mark will go over this with you at one of our first meetings, and he'll show you how to enter training information into DM. 


### DOI Talent

DOI Talent is the platform for administering online training to Department of the Interior Employees. Even though you're not an actual federal employee, you'll still need to get set up with an account on DOI Talent. Again, Sarah Romero will be able to help.


### Student symposium

As a student in the Coop Unit you'll have the opportunity to participate in the annual Student Symposium, which is held during the fall quarter. You'll also get the chance to interact with agency scientists and managers from state and federal agencies.


### Vehicles and boats

The Coop Unit has its own group of vehicles and boats that are available only to us. Before you can use or even ride in them, you'll need to fill out a federal volunteer form. Sarah Romero can help you with this. Before you can drive any of the boats, you need to complete both the [Washington State Boater Education course](https://parks.state.wa.us/442/Mandatory-Boater-Education) and the [USGS Motorboat Operator Certification Course (MOCC)](https://water.usgs.gov/admin/memo/policy/wrdpolicy96.25.html). For specific information, check out the [Boats Section](https://scheuerell-lab.github.io/lab-book/boats.html).


