# Participation


## Mentoring meetings

Every student is expected to set up regular mentoring meetings with Mark, which occur either every week or every other week, depending on the needs of the student. These meetings are usually scheduled for one hour, but the day and time may change to reflect changes in student coursework, committee meetings, etc. Students should come prepared to discuss goals and/or problems they're having with field/lab work, analyses, personnel, etc.

## Lab meetings

Attendance and participation at lab meetings is mandatory. If you are unable to attend, please notify Mark in advance. We currently meet every week, with the day and time varying by quarter to accommodate everyone's schedules.

## SAFS seminar

Attendance at the weekly SAFS seminar on Thursday afternoons is mandatory. During Fall and Spring quarters, seminars run from 4:00-5:00. You can find the schedule for Fall and Spring [here](https://fish.uw.edu/news-events/seminar-series/departmental-seminars/). During Winter quarter, SAFS host the Bevan Seminar Series, which runs from 4:30-5:30 to align with normal course begin/end times. You can find the schedule [here](https://fish.uw.edu/news-events/seminar-series/bevan-series/).

## SAFS quantitative seminar

Attendance at the SAFS weekly quantitative seminar is optional, but strongly encouraged. Seminars run from 12:30-1:30 on Fridays in FSH 203. You can find the schedule [here](https://fish.uw.edu/news-events/seminar-series/quantitative-seminar/).

## Fish & Wildlife Ecology seminar

Attendance at the weekly Fish & Wildlife Ecology seminar is optional, but strongly encouraged. Seminars are organized by Alex McInturff and there is a mailing list you can sign up for here. Day and times of these seminars vary by quarter and year. To subscribe to the mailing list,

1) Sign in to [Google Groups](https://groups.google.com/).

2) Click **All groups** and find the group that you want to join.

3) Click **Join group**.

4) If you want to link or unlink your Google profile, choose an option:

* If you don't want people to view your Google profile, uncheck the **Link to my Google account profile** box. You can also enter a different display name for people to see.

* If you want people to view your Google profile, check the **Link to my Google account profile** box.

5) In the **Subscription section**, choose how often you want email updates from the group:

* Every new message

* Send daily summaries

* Combined updates

* Don't send email updates

6) Click **Join group**.

