# Presentations

You will have many opportunities to present your research in both informal and formal settings. In most cases, this will involve some form of oral presentation, but sometimes you may elect to, or be asked to, create a poster presentation. If you are new to these experiences, Mark will work with you on both the content and format of your talk or poster. And if you are more experienced, Mark will likely offer some advice as well.

## Lab meetings

Lab meetings are a great place to present your research because you know everyone and you can trust them to be both honest and polite in their critiques. If you are planning to give a presentation at an upcoming workshop, conference, or seminar series, Mark will very likely ask you to give a practice presentation to the lab.

## Public outreach

### Community engagement

We often have opportunities to present our research to the public as part of organized activities (eg, "Science on Tap" events at a local brewery) or casual conversations in the field (eg, people _love_ to ask questions at boat ramps). Engaging with the public is important because they are genuinely curious and eager to learn, and as taxpayers they support us indirectly.

### SEAS

[Students Explore Aquatic Sciences (SEAS)](https://fish.uw.edu/alumni-community/students-explore-aquatic-sciences-seas/) is a volunteer-run outreach program operated by undergraduates, graduate students, and staff in SAFS. Their goal is to help increase access to science for underserved students in the Seattle area by helping people/labs in SAFS (and elsewhere) to develop outreach materials for use in K-12 classrooms. Mark encourages people in the lab to learn more about SEAS, and consider volunteering with them. (Aside: SEAS also organizes the [Aquatic Sciences Open House](https://fish.uw.edu/students/student-organizations/students-explore-aquatic-sciences-seas/uw-aquatic-science-open-house/) every May.)

## Formal

### Seminars & guest lectures

You may be invited to give a presentation in a regular seminar series or in a course at UW (eg, SAFS Quantitative, Fish & Wildlife Ecology), or beyond. If so, please ask Mark about whether it's appropriate given your other commitments, or if you would like some cover to pass on the invite. That said, Mark is a big supporter of these activities, so he will almost certainly agree.

### Conferences & symposia

In general, Mark will cover the registration and travel costs for students to travel to one scientific conference per year, with the assumption that they will be presenting their research. These are great opportunities to learn about the latest advances in our field, see old friends, and build our professional networks. Most conferences have abstract submission deadlines early in Jan-Mar, so the lab will typically discuss possible venues in late fall. If there is a particular conference that you are interested in, please let Mark know as soon as possible so we can start our planning.

