# (PART) Professional expression {-}

# Communication

Communication is a critical component of science, whether it be through formal and informal publications, seminars, conference presentations, or a quick chat in the hall. Sharing our information with others and learning from one another are necessary for us to advance our collective knowledge.

Our lab relies on several forms of communication, each with its own pros and cons. First and foremost, Mark maintains an "open door" policy when he's in his office. If the door is wide open, please come on in. If the door is open just a crack, please knock, as Mark may be on the phone or meeting with someone else. If the door is closed, please assume that either Mark does not want to be bothered or that he's out of the office.

## Website

Mark encourages everyone to create a personal website, as they are a great way to show your CV, the projects you work on, people you collaborate with, etc. There are many different platforms that allow you to create a free website. Mark uses Hugo and reveal.js to create the lab website on GitHub and would be happy to help you get set up that way. Alternatively, you can use Google, Wix, Wordpress, etc.

## *Curriculum vitae*



## Social Media


