# Publications

<br>

Writing is a large part of our scientific endeavors, and as a member of our lab you should expect to be integrally involved in communicating the results of your research. Writing can be hard and it may take a lot of practice before one feels confident in their ability to communicate clearly and effectively. Mark is willing to help you with the writing process, but he will not write things for you.

## Authorship

Our research typically involves a wide variety of collaborators. When deciding who should be included as an author on any publication, we will follow APA guidelines, which state:

> Authorship credit should reflect the individual's contribution to the study. An author is considered anyone involved with initial research design, data collection and analysis, manuscript drafting, and final approval. However, the following do not necessarily qualify for authorship: providing funding or resources, mentorship, or contributing research but not helping with the publication itself. The primary author assumes responsibility for the publication, making sure that the data are accurate, that all deserving authors have been credited, that all authors have given their approval to the final draft; and handles responses to inquiries after the manuscript is published.

Authorship will be discussed prior to the beginning of a new project, so that expectations are clearly defined. However, changes to authorship may occur over the course of a project if a new person becomes involved or if someone is not fulfilling their planned role. In general, Mark expects that graduate students and postdocs will be first authors on publications on which they are the primary lead, and Mark will be a co-author. Some labs use a tradition where the PI is the last author, but Mark prefers to list authors in order of contribution, which means that sometimes he will be last and other times he may be second, third, etc.

## USGS Fundamental Science Practices

Because Mark is an employee of the U.S. government, he and his lab members must follow a set of policies and procedures for ensuring the quality and integrity of our science, which includes our scientific communications, known as the  [Fundamental Science Practices (FSP)](https://www.usgs.gov/about/organization/science-support/office-science-quality-and-integrity/fundamental-science-practices). To comply with FSP, there are several steps we must take before a manuscript may be published. Failure to do so causes a number of problems, and could potentially result in disciplinary action against Mark.

### Affiliation

It is <strong>very important</strong> that Mark's affiliation be listed as:

> U.S. Geological Survey Washington Cooperative Fish and Wildlife Research Unit  
> School of Aquatic and Fishery Sciences  
> University of Washington  
> Seattle, WA

Although there may be some subtle differences depending on the journal/outlet, such as the inclusion of a street address or zip code, the first line must always be written verbatim as above. Note, too, that you may not abbreviate the first line in any manner (eg, "USGS WACFWRU").

Students and postdocs should list their affiliation as

> School of Aquatic and Fishery Sciences  
> University of Washington  
> Seattle, WA

although QERM students may elect to use

> Quantitative Ecology and Resources Management  
> University of Washington  
> Seattle, WA


### Pre-publication disclaimer

As part of the [USGS Fundamental Science Practices](https://www.usgs.gov/office-of-science-quality-and-integrity/fundamental-science-practices), publications with Mark s a co-author <strong>must</strong> include the following statement on the cover page or somewhere else near the beginning when formatting a paper for submission to a journal:

> This draft manuscript is distributed solely for purposes of scientific peer review. Its content is deliberative and predecisional, so it must not be disclosed or released by reviewers. Because the manuscript has not yet been approved for publication by the U.S. Geological Survey (USGS), it does not represent any official USGS finding or policy.

### Product disclaimer

If we refer to specific trade, firm, or product names within a publication (eg, "R programming language", "YSI multisonde"), we <strong>must</strong> include the following statement in the acknowledgments:

> Any use of trade, firm, or product names is for descriptive purposes only and does not imply endorsement by the U.S. Government.

### Bureau approval

At the point we are ready to submit a manuscript to a journal, there is a formal internal review process that Mark must follow. Here are the steps:

1) Mark finds a "friendly" reviewer who is willing to provide comments on the paper akin to those we might expect from an unknown reviewer at a journal (ie, they must be rigorous but hopefully not too onerous).

2) Mark uploads a reviewer form with information about the manuscript and person identified in (1), along with clean copies of the manuscript and all supplemental material(s).

3) Mark asks his regional supervisor to approve the person identified in (1).

4) We send the paper to the target journal and the person identified in (1), and wait for comments to come back.

5) We address all of the comments from (4), in a point-by-point manner, in either separate documents or inline via the track changes option if comments were provided in that manner (eg, this is common with friendly reviewers). Note that we do not have to comply with every request, but we do need to address every comment, even if that means we simply say something like "We respectfully disagree because..." or "This is a great idea but it's out of the scope of the current study".

6) Mark uploads all of the comments from (4) and our responses from (5), along with a clean revised manuscript.

7) Mark requests formal manuscript approval from his Bureau Approving Officer (BAO). This process typically takes 1-2 weeks.

__Note__: Under no circumstances can we allow a journal to post a preprint, online early, or other draft of our paper _before_ Mark gets the BAO's approval.


## Old projects

For projects that required significant lab resources (eg, time, money, labor), project "ownership" expires 3 years after data collection has ended (or whenever the original primary lead relinquishes their rights to the study, whichever comes first). At that point, Mark reserves the right to re-assign the project as needed to expedite publication. This policy is intended to avoid situations in which a dataset languishes for a long period of time, while still giving publication priority to the original primary lead. 

## Informal SciComm

To the extent that your time and interest allows, I support people writing informal posts/threads on social media, blogging, etc. Effective and engaging science communication is a skill that takes time to develop, and your experiences at SAFS, UW, and beyond will provide ample opportunities for practice. Mark's only requirement is that anything you share adhere to our [Code of Conduct] and abide by the [Conversation Norms] agreed to with others.

NOTE: SAFS' Communications Manager, [Niamh Owen-McLauglin](mailto:nowenmcl@uw.edu), is always looking for stories, articles, pictures, etc that she can share on the SAFS website and social media platforms. Several current and former lab members have been featured in the past. Feel free to reach out to her (and cc Mark) if you have something related to your research, outreach activities, or awards that you think could be of possible interest to others.
