# Reporting and support

<br>

## All lab members

### SAFS Anonymous Reporting Tool

If you would like to report an incident to SAFS leadership, but remain anonymous, please use the [SAFS online reporting form](https://forms.gle/mmRmT1GTkNwaoF198) (requires a UW net-ID to access).

### College of the Environment Resource List

This [list of resources](http://environment.uw.edu/about/diversity-equity-inclusion/non-discrimination-and-sexual-harassment-resources), compiled by the College of the Environment, includes information on reporting and getting support for bias incidents, discrimination, and harassment.

### UW Bias Reporting Tool

If you encounter or suspect incidents of bias, you are encouraged to use [this tool](http://washington.edu/bias) to file a report, which will be reviewed by the UW’s Bias Incident Advisory Committee. Whenever possible, bias reports will be reviewed within two to four business days. Possible outcomes to reports are listed on the reporting tool webpage.
 
### Employee Assistance Program (UW employees only)

The Washington State [Employee Assistance Program](https://hr.uw.edu/worklife/employee-assistance-program/) (WA EAP) supports PEBB-eligible University of Washington employees and their household members to help identify and resolve personal concerns to promote individual and workplace wellbeing. WA EAP can connect individuals with free and confidential mental health counseling, legal services, financial counseling, and more.

### SafeCampus

[SafeCampus](http://washington.edu/safecampus) is the University of Washington’s violence-prevention and response program. SafeCampus supports students, staff, faculty, and community members in preventing violence. Call SafeCampus anytime—no matter where you work or study—to anonymously discuss safety and well-being concerns for yourself or others.
 
### Office of the Ombud

The [Office of the Ombud](http://washington.edu/ombud) serves the UW community by providing high quality, client-focused services for preventing, managing, navigating and resolving conflict at the UW. Through active participation in the problem-solving process, clients develop the ability to prevent, manage, and resolve future conflicts. Read more about [what to expect](https://www.washington.edu/ombud/what-to-expect/) here.

### Civil Rights Investigation Office

The [Civil Rights Investigation Office](https://www.washington.edu/cr-investigations/) investigates complaints made about University employees and students that raise concerns relating to civil rights such as protection from discrimination, harassment, retaliation, and sexual misconduct. The site provides information on [campus resources](https://www.washington.edu/cr-investigations/resources/) and UW [policies and procedures](https://www.washington.edu/cr-investigations/policy-and-procedure/). Individuals can read an [overview of the reporting process](https://www.washington.edu/compliance/tixio/) and/or speak with a [confidential advocate](https://www.washington.edu/sexualassault/support/advocacy/) to discuss their options. (**Note**: The University Complaint Investigation and Resolution Office [UCIRO] and the Title IX Investigation Office (TIXIO) are now collectively the Civil Rights Investigation Office.)
 
### Your Union

[UAW 4121](https://www.uaw4121.org/) supports Academic Student Employees, Postdocs, and, most recently, Research Scientists and Engineers. UAW 4121 encourages members to [contact them](https://www.uaw4121.org/member-center-2/know-your-rights/what-do-i-do-if-i-have-a-problem/) immediately whenever they have a concern, problem, or question about any aspect of their work.
 
### Environmental Health and Safety

[This reporting tool](http://ehs.washington.edu/report-concern) is for non-emergency incidents that occur on University of Washington owned or leased property that involve a University student; staff, faculty, or other personnel; or a visitor.
 

## Students only

### Husky HelpLine (UW students only)

The [HuskyHelpLine](https://wellbeing.uw.edu/huskyhelpline/) exists to give students access to same-day, confidential mental health and crisis intervention support. It is available 24-hours a day and  in multiple languages. Students can connect with the HuskyHelpLine via phone (US & Canada: 206-616-7777 | abroad: 001-416-380-6578), online chat, or the Telus app. (Husky HelpLine is supported through Telus and was formally called MySSP.)

### College of the Environment Academic Grievance Procedures (CoENV students only)

In the College of the Environment, faculty, mentors, and departmental leaders [welcome student feedback](https://environment.uw.edu/intranet/academics/academic-policies/student-academic-grievance-procedures/), including criticisms and grievances. All grievances are respected and treated seriously. The College of the Environment Student Academic Grievance Procedures provide mechanisms for graduate and undergraduate students to address academic problems or grievances in an equitable, respectful, and timely manner. Academic grievances are those involving conflicts between students and faculty instructor(s) or mentor(s) with respect to differences arising within credit-bearing coursework, research, and/or mentoring
while the students are registered at UW.
 
### Graduate Student Academic Grievance Procedures (UW graduate students only)

This is an [overview of the grievance procedures](https://grad.uw.edu/policies/3-8-academic-grievance-procedure/) available to UW graduate students. Grad students who believe they have been subjected to unfair treatment in the administration of academic policies may, except as noted, seek resolution of their complaints under this Academic Grievance Procedure. This applies, but is not limited, to the application of departmental, college, or Graduate School policies; deviations from stated grading practices (but not individual grade challenges); unfair treatment; and related issues.

### Student Legal Services (UW students only)

[Student Legal Services](http://depts.washington.edu/slsuw/) (SLS) is an on-campus law office that provides a safe and confidential space for all UW-Seattle and Bothell students who have legal questions or concerns. They offer free 40-minute consultations on a broad range of issues. Students can also hire ongoing representation for a low hourly rate. SLS is located in Husky Union Building (HUB) 306.
