# Safety

###  **If you are experiencing an emergency, dial 911 immediately!** {-}

<br>

## SafeCampus

If you feel unsafe or at-risk in any way while on campus, contact [SafeCampus](https://www.washington.edu/safecampus/) (206-685-7233) anytime&ndash;&ndash;no matter where you work or study&ndash;&ndash;to anonymously discuss safety and well-being concerns for yourself or others. SafeCampus can provide individualized support, discuss short- and long-term solutions, and connect you with additional resources when requested. 

## Emergency contacts

Our lab keeps a confidential list of emergency contacts for every member of the lab. If you have not yet done so, please fill out [this form](https://forms.gle/i3Qpvajjh7aK4Gp98) with the name and contact information of at least one person you would to be contacted in the event of an emergency.

## Lab

[more info coming soon]

## Field

**NOTE**: Click [here](resources/Scheuerell_fieldwork_safety_plan_2022.pdf) to access our full field safety document.

### General considerations

-	When going into the field, someone else should always be told where you’re going, and when you anticipate being back. For on-the-water activities, the trip leader should file [a detailed float plan](resources/float_plan.pdf).

-	When heading into remote areas, have detailed physical maps with you and a compass. Relying on technology or cell service without any physical map backups is a bad idea.

-	If you carry an epipen or similar device, make sure someone else in the group knows where it is and how to use it, in case you are unable to administer it yourself in an emergency.

And always remember: **People’s safety is more important than any sample!**


## UW safety resources

* [UW Environmental Health & Safety (EH&S)](https://www.ehs.washington.edu/)

* [UW Lab Safety Manual](https://www.ehs.washington.edu/resource/laboratory-safety-manual-510)

* [UW Online Accident Reporting System (OARS)](https://www.ehs.washington.edu/ohsoars)

* [Chemical Inventory & Safety Data Sheets (MyChem)](https://cspc.admin.uw.edu/mychem/uwnetid/home/greeting.aspx)

