# Scientific Integrity

## Reproducible research {#reproducible}

One of the hallmarks of our lab is that we are advocates and practitioners of "open and reproducible research". Open research means we use public online platforms for hosting our code and workflows. Reproducible research means that an analysis can be reproduced exactly as originally intended, even if it's years later. Conducting reproducible research is more difficult than it sounds, because it requires you to be organized and possess sufficient foresight to document each step of your research process. There are three main things you can do to improve the reproducibility of your research:

1) write extensive documentation  
2) create programming workflows, and
3) use formal version control.

Documentation can be in the form of liberal comments in coding scripts, such that others can easily decipher what the code is doing, as well as documents that combine text, equations, code, and results (see the [Markdown section](#markdown) below). Programming workflows help with reproducibility because they take some of the human element out, and in an ideal scenario, you are left with a script or series of scripts that takes data from raw form to final product. Programming alone is not enough, though, because people can easily forget which script changes they made and when. Therefore, all projects that involve programming of any kind (so basically, all projects) must use some form of version control. Our lab uses Git (a version control software) in combination with GitHub (an online collaboration platform). This is a hard requirement because

* it allows us to definitively track the evolution of files over time,  
* it allows for easier detection of bugs, and  
* it facilitates code sharing.

### References

Mark encourages people to take a look at these references on scientific computing and project workflows:

* [Bryan (2018) Excuse me, do you have a moment to talk about version control?](resources/Bryan_2018_version_control.pdf)

* [Cooper & Hsing (2017) A guide to reproducible code in ecology and evolution](resources/BES-guide-to-reproducible-code.pdf)

* [Marwick et al. (2018) Packaging data analytical work reproducibly using R (and friends)](resources/Marwick_et_al_2018_research_compendia.pdf)

* [Wilson et al. (2017) Good enough practices in scientific computing](resources/Wilson_et_al_2017_good_enough_computing.pdf)

### GitHub

GitHub is a code hosting platform for version control and collaboration. It lets you and others work together on projects from anywhere. GitHub itself is not a development tool, but rather a file hosting and collaboration site. In many ways, a social network like Facebook. You can build a profile, create projects to share with others, and follow the accounts of other users. GitHub is not linked to any one programming language like R, as you can find all kinds of projects based upon different languages there. GitHub also runs Git in the background. Git is a version control software, which means it records changes to a file or set of files over time so that you can recall specific versions later. 

Our lab maintains a so-called "organization" on GitHub [here](https://github.com/scheuerell-lab). Each project gets its own "repository" (or "repo"), which you can think of as the root directory for various folders and files. Each repository also contains a `README` file with information about its contents and a `LICENSE` file that lays out permissions and conditions for others who are interested in our work. You can learn more about GitHub and how to set up a repo [here](https://fish497.github.io/website/lectures/week_02/lec_04_intro_github.html).

### Markdown {#markdown}

Markdown is a simple markup language for creating formatted text using a plain-text editor. It makes use of some special characters for formatting headers and text. GitHub automatically recognizes Markdown files with a `.md` extension and renders them as formatted information.

R Markdown is a specific flavor of Markdown that allows you great flexibility to include equations and other special formats. It also allows to create documents in various forms such as HTML (`.html`), PDF (`.pdf`), and even MS Word (`.doc`). You can learn more about using Markdown [here](https://fish497.github.io/website/lectures/week_02/lec_04_intro_github.html#Markdown).

## Authorship

We will follow APA guidelines with respect to authorship:

> Authorship credit should reflect the individual's contribution to the study. An author is considered anyone involved with initial research design, data collection and analysis, manuscript drafting, and final approval. However, the following do not necessarily qualify for authorship: providing funding or resources, mentorship, or contributing research but not helping with the publication itself. The primary author assumes responsibility for the publication, making sure that the data are accurate, that all deserving authors have been credited, that all authors have given their approval to the final draft; and handles responses to inquiries after the manuscript is published.

Authorship will be discussed prior to the beginning of a new project, so that expectations are clearly defined. However, changes to authorship may occur over the course of a project if a new person becomes involved or if someone is not fulfilling their planned role. In general, Mark expects that graduate students and postdocs will be first authors on publications on which they are the primary lead, and Mark will be a co-author. Some labs use a tradition where the PI is the last author, but Mark prefers to list authors in order of contribution, which means that sometimes he will be last and other times he may be second, third, etc.

## Old projects

For projects that required significant lab resources (i.e., time, money, or lab effort), project "ownership" expires 3 years after data collection has ended (or whenever the original primary lead relinquishes their rights to the study, whichever comes first). At that point, Mark reserves the right to re-assign the project (or not) as needed to expedite publication. This policy is intended to avoid situations in which a dataset languishes for a long period of time, while still giving publication priority to the original primary lead. 


