# Vehicles

<br>

The Coop Unit has its own fleet of federally owned vehicles that are available only to faculty, students, and staff in the Unit. Importantly, you must fill out a federal volunteer form _before you can even ride in_ any of the Unit's vehicles (Mark can help you with this). Note, too, that you must complete a defensive driving course _before you can drive_ any of the vehicles (see below).


## Fleet

| Make & model | License plate | Occupants | Capable of towing?
|:-------------------|:-------------------------:|:-----:|:----:|
| Chevy HHR | I433302 | 4 | No |
| Chevy Suburban 4x4 | I434802 | 7 | Yes |   
| Chevy Silverado 4x4 | I433148 | 2 | Yes |
| Ford F-350 4x4 | I434891 | 4 | Yes |
| | | 

Please do your best to select a vehicle most appropriate for your purpose. For example, if you and a colleague are going to a meeting in Olympia, the Chevy HHR would be a better choice than the Chevy Suburban.

Please try your best to keep the vehicles clean and empty of all trash, tools, first aid kits, field gear, etc. We have had incidents in the past where people have broken windows and stolen various contents.


## Training

Before operating any of the Unit's vehicles, you will need to take a defensive driving course, which is good for three years. The course is offered online and takes about 3 hours to complete. Mark will provide you with the URL and password to access the course. 

## Operation 

### Reservations

We use a shared Google calendar for making vehicle reservations; Mark will add you to the user list. Please reserve a vehicle in advance of any trip and make sure no one else has a reservation that would conflict with yours (e.g., you're planning to have a vehicle for several days and return on a Thursday, but someone else has planned to use the vehicle on Wednesday). Reservations should be added to the calendar as

> LastName - VehicleName - Destination

Make sure you indicate your estimated dates/times of departure and arrival on the reservation as well.


### Keys

All of the vehicle keys are kept inside the Coop Unit suite (FSH 242D). Each vehicle has its own clipboard containing keys and a gas purchase log. Make sure to take the proper clipboard with you.


### First aid & assistance kits

You should take one of the first aid kits and roadside assistance kits with you when you expect to be out of the immediate Seattle area. You can find them on the shelf just inside the door to FSH 242D near the keys.


### Trailering

If you need to tow a trailer, make sure to select the right vehicle for the task. All of our vehicle hitch mounts have a fixed 2" receiver, but we don't leave the hitches/balls attached to the receiver to avoid theft. There are several hitches on the shelf and floor on the same shelf with the first aid and assistance kits. Make sure the hitch has the proper drop for the trailer you are towing. Please ask Mark if you are unsure about any of this. 


### Parking

The vehicles are typically parked on campus in lot W21, which is east of SAFS, west of Genome Sciences, and north of Agua Verde. On some occasions, there may be special events, construction, or other activity that will preclude you from parking in W21 when you return from your trip. If so, please park the vehicle in one of the nearby lots (see the map at the bottom of the vehicle mileage form). In theory, you should be able to park in any state-owned parking lot without issue, but please pay particular attention to any signage indicating possible restrictions.

### Mileage & budget

When using a Unit vehicle, please make note of the beginning and ending mileage, as you will need to record these at the conclusion of your trip. Mark suggests using your phone to take a picture of the odometer before heading out to facilitate this process, but you can edit the mileage form after the fact.
s
To access the mileage form, use the camera on your phone to scan the QR code on the cover of the clipboard, which will open a web browser and take you to the form. There are several fixed fields with dropdown menus from which to select your options:

* Driver's name  
* Budget number & name  
* Vehicle name  

You will have to manually enter the following:

* Date  
* Beginning mileage  
* Ending mileage  

Lastly, use the radio buttons to select the lot where the vehicle was parked.

